development:
  adapter: postgresql
  encoding: utf8
  database: not_ramen_dev
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: utf8
  database: not_ramen_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: not_ramen_production
  pool: 5
  timeout: 5000