# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49b94a402f35152a0e393c2ee6b39c06c1f31266b0ad324af0528dcae7ff88daa3e1487052277920b94d73f71a4f1163980da51d52e8fd8287ff82725ee74328

test:
  secret_key_base: c2142c9c09ab21765048d1b024052effb7d5f88a9088f06910d826e37a49beb9cf22972642534f6b33ef85a0dbd7f960f06e419b780a54c8ec1d811f9657569d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
